##
## EPITECH PROJECT, 2018
## cpp_d13_2018
## File description:
## Makefile
##

all:	tests_run

tests_run:
	@make -C ./tests/ tests_run

clean:
	@make -C ./tests/ clean

fclean:
	@make -C ./tests/ fclean

re:
	@make -C ./tests/ re

.PHONY: all tests_run clean fclean re
