##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Makefile rush2
##

FILE	=	main.c	\
		tab.c	\
		det_language.c	\
		little_fonc.c

NAME	=	rush2

all:	compil

compil:
	gcc -o $(NAME) $(FILE)

clean:
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean	all
