##
## EPITECH PROJECT, 2022
## OOP_arcade_2018
## File description:
## Makefile
##

all:	nibbler pacman minesweeper

nibbler:
	@make -C nibbler/

pacman:
	@make -C pacman/

minesweeper:
	@make -C minesweeper/

clean:
	@make -C nibbler/ clean
	@make -C pacman/ clean
	@make -C minesweeper/ clean

fclean:
	@make -C nibbler/ fclean
	@make -C pacman/ fclean
	@make -C minesweeper/ fclean

re:
	@make -C nibbler/ re
	@make -C pacman/ re
	@make -C minesweeper/ re

.PHONY: all nibbler pacman minesweeper clean fclean re
