export default {
  GET_USER_TOKEN: 'GET_USER_TOKEN',
  GET_USER_TOKEN_SUCCESS: 'GET_USER_TOKEN_SUCCESS',
  GET_USER_TOKEN_ERROR: 'GET_USER_TOKEN_ERROR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_LOADING: 'LOGIN_REQUEST_LOADING',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_ERROR: 'LOGIN_REQUEST_ERROR',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
  LOGOUT_REQUEST_ERROR: 'LOGOUT_REQUEST_ERROR',

  CLEAN_USER_TOKEN: 'CLEAN_USER_TOKEN',
  CLEAN_USER_TOKEN_SUCCESS: 'CLEAN_USER_TOKEN_SUCCESS',
  CLEAN_USER_TOKEN_ERROR: 'CLEAN_USER_TOKEN_ERROR',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_REQUEST_LOADING: 'REGISTER_REQUEST_LOADING',
  REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
  REGISTER_REQUEST_ERROR: 'REGISTER_REQUEST_ERROR',
  REGISTER_REQUEST_CLEAR: 'REGISTER_REQUEST_CLEAR',

  RECOVER_PASSWORD_REQUEST: 'RECOVER_PASSWORD_REQUEST',
  RECOVER_PASSWORD_LOADING: 'RECOVER_PASSWORD_LOADING',
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RECOVER_PASSWORD_ERROR: 'RECOVER_PASSWORD_ERROR',
  RECOVER_PASSWORD_CLEAR: 'RECOVER_PASSWORD_CLEAR',
};
