##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## infin add
##

FILE	=	main.c	\
		fcommu.c	\
		add_pos.c

NAME	=	infin_add

all:	compil

compil:
	gcc -o $(NAME) $(FILE)

clean:
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean all
