##
## EPITECH PROJECT, 2022
## OOP_arcade_2018
## File description:
## Makefile
##

all:	ncurses sfml libcaca

ncurses:
	@make -C ncurses/

sfml:
	@make -C sfml/

libcaca:
	@make -C libcaca/

clean:
	@make -C ncurses/ clean
	@make -C sfml/ clean
	@make -C libcaca/ clean

fclean:
	@make -C ncurses/ fclean
	@make -C sfml/ fclean
	@make -C libcaca/ fclean

re:
	@make -C ncurses/ re
	@make -C sfml/ re
	@make -C libcaca/ re

.PHONY: all ncurses sfml libcaca clean fclean re
