##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Mk 101pong
##

all:	compil

compil:
	gcc -o 101pong main.c -lm

clean:
	rm -f *~

fclean:	clean
	rm -f 101pong

re:	fclean all

.PHONY: all clean fclean re
