##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Rush3
##


SRC	=	main.c	\
		display.c

NAME	=	rush3

all:	$(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC) -I./include/

clean:
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean all
