##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Makefile
##

FILE	=	my_cat.c

NAME	=	cat

all:	compil

compil:
	gcc -o $(NAME) $(FILE)

clean:
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean	all
