##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## do-op
##

FILE	=	doop.c	\
		doop2.c

NAME	=	do-op

all:	compil

compil:
	gcc -o $(NAME) $(FILE)

clean:
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean all
